spring.application.name=trabalhoP1

# 1. Adicionado o prefixo correto e URL limpa
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres

# 2. Usuário com o ID do projeto (Obrigatório para a porta 6543)
spring.datasource.username=postgres.jsbqjuetsqxnkibksaxt

# 3. Sua senha
spring.datasource.password=Amores222320!

# Configurações do Hibernate/Driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true