spring.application.name=trabalhoP1
server.port=${PORT:8081}

# 1. Aponta para o seu computador (localhost) na porta padrão do Postgres (5432)
# Substitua "nome_do_seu_banco" pelo nome do banco que você criou no Passo 1
spring.datasource.url=jdbc:postgresql://localhost:5432/trabalhoP1

# 2. Seu usuário local do Postgres (geralmente é postgres)
spring.datasource.username=postgres

# 3. A senha que você configurou ao instalar o Postgres na sua máquina
spring.datasource.password=post222320

# Configurações do Hibernate/Driver (permanecem iguais)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true